# Generated by Django 3.2.6 on 2021-09-21 10:18

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='courses/images.jfif', null=True, upload_to='', verbose_name=django.contrib.auth.models.User),
        ),
    ]
