# Generated by Django 3.2.6 on 2021-09-09 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
