# Generated by Django 3.2.6 on 2021-09-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='hit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
